language: c
os: linux

# Doesn't work, the build matrix includes only xenial...
#dist:
#- xenial
#- bionic
#- focal
#arch:
#- amd64
#- s390x
#- arm64
#- ppc64le

jobs:
  include:
  - arch: amd64
    dist: xenial
  - arch: amd64
    dist: bionic
  - arch: amd64
    dist: focal
  - arch: s390x
    dist: xenial
  - arch: s390x
    dist: bionic
  - arch: s390x
    dist: focal
  - arch: arm64
    dist: xenial
  - arch: arm64
    dist: bionic
  - arch: arm64
    dist: focal
  - arch: ppc64le
    dist: xenial
  - arch: ppc64le
    dist: bionic
  - arch: ppc64le
    dist: focal

script: ./script.sh

notifications:
  email: false
